name: Jekyll site CI

on:
  push:
    branches: [ pre-2020-06 ]
  pull_request:
    branches: [ pre-2020-06 ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
